### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by ToJen** [oclif/plugin-warn-if-update-available#11]
The README says

> In package.json, set oclif['warn-if-update-available'].timeoutInDays to change the timeout duration between checks.

Where does this go exactly in the `package.json`?

**Comment by kinetifex** [comment]
Here's an example partial of what your package.json might look like:
```json
{
  "dependencies": {
    "@oclif/command": "^1.4.33",
    "@oclif/plugin-warn-if-update-available": "^1.5.1"
  },
  "oclif": {
    "commands": "./src/commands",
    "plugins": [
      "@oclif/plugin-warn-if-update-available"
    ],
    "warn-if-update-available": {
      "timeoutInDays": 7
    }
  }
}
```

Hope tht helps.
