### ISSUE TITLE
Checking for plugins update?

### ISSUE THREAD

**Issue by ktalebian** [oclif/plugin-warn-if-update-available#111]
Is there a way to use this plugin to check for the plugins installed in your CLI?

**Comment by timmydoza** [comment]
I have the same question. This library can be used to remind users to upgrade their CLI.  But can it be used to remind users to upgrade their CLI Plugins?

**Comment by mdonnalley** [comment]
Checking for outdated plugins is outside the scope of this plugin. However, this is something that you can easily implement in your own plugin if you wanted to.
