### ISSUE TITLE
support for distribution via `oclif-dev publish` and S3?

### ISSUE THREAD

**Issue by samuela** [oclif/plugin-warn-if-update-available#20]
Is there any support for checking for updates based on a project published via `oclif-dev publish` as opposed to npm? It seems like it shouldn't be necessary to publish to two places in order to get upgrade warnings working.

**Comment by jdxcode** [comment]
there isn't currently any support for that. I was more concerned about CLIs in npm and not in tarballs vs the other way around. In past versions of the CLI we had a manifest file that was published alongside the CLI which could be used here.

**Comment by samuela** [comment]
`oclif-dev publish` maintains a version file, `my-bucket/version`:
```
{
  "version": "0.0.3",
  "baseDir": "nuvemfs",
  "channel": "stable",
  "gz": "https://s3-us-west-2.amazonaws.com/nuvemfs-cli-assets/nuvemfs-v0.0.3/nuvemfs-v0.0.3.tar.gz",
  "xz": "https://s3-us-west-2.amazonaws.com/nuvemfs-cli-assets/nuvemfs-v0.0.3/nuvemfs-v0.0.3.tar.xz",
  "sha256gz": "19920b5fc31a0542e49da6ae06db3a86a4ea04516d4e5f18f9b92fa5e7f5cb2b",
  "rollout": false,
  "node": {
    "compatible": ">=8.0.0",
    "recommended": "11.8.0"
  }
}
```
It seems like that could be used pretty easily here.

**Comment by jdxcode** [comment]
Oh good, looks like I planned ahead there. I'd accept a PR to use that as optional behavior

**Comment by mdonnalley** [comment]
Closing since this has gone stale.
