### ISSUE TITLE
Display warning less frequently

### ISSUE THREAD

**Issue by childish-sambino** [oclif/plugin-warn-if-update-available#21]
If a new version of the CLI is found, _every_ subsequent command execution displays the warning message. I'd prefer an option to specify how often the warning message should be displayed.

**Comment by cjcodes** [comment]
This is particularly troubling when CLIs implement autocomplete, which requires calling the CLI from the shell's profile. The update prompt comes up every time the user starts a new shell.

**Comment by psanders** [comment]
This gets a bit frustrating for end-users. A `frequency` option would be nice.
