### ISSUE TITLE
Does not seem to work with scoped packages

### ISSUE THREAD

**Issue by bader-nasser** [oclif/plugin-warn-if-update-available#423]
The plugin does not show any messages in my application after switching to use scoped package. I used to get a message to update my application because there was an other package with the same name (`pdftools`) on npm!

```json5
{
	"name": "@bader-nasser/pdftools",
	"bin": {
		"pdftools": "bin/run.js",
		"pdf-tools": "bin/run.js"
	},
	"repository": "bader-nasser/pdftools",
        "dependencies": {
		"@oclif/core": "^2.15.0",
		"@oclif/plugin-autocomplete": "^2.3.8",
		"@oclif/plugin-help": "^5.2.19",
		"@oclif/plugin-not-found": "^2.4.1",
		"@oclif/plugin-plugins": "^3.4.2",
		"@oclif/plugin-warn-if-update-available": "^2.1.0",
	},
	"devDependencies": {
		"@oclif/test": "^2.5.3",
		"oclif": "^3.15.0",
	},
	"files": [
		"/bin",
		"/dist",
		"/npm-shrinkwrap.json",
		"/oclif.manifest.json",
		"/data.schema.json"
	],
	"oclif": {
		"bin": "pdftools",
		"binAliases": [
			"pdftools",
			"pdf-tools"
		],
                // not sure about this property, and couldn't find any docs if it affects the plugin
		"scope": "bader-nasser",
		"dirname": "pdftools",
		"commands": "./dist/commands",
		"additionalHelpFlags": [
			"-h"
		],
		"additionalVersionFlags": [
			"-v"
		],
		"plugins": [
			"@oclif/plugin-help",
			"@oclif/plugin-plugins",
			"@oclif/plugin-autocomplete",
			"@oclif/plugin-not-found",
			"@oclif/plugin-warn-if-update-available"
		],
		"warn-if-update-available": {
			"timeoutInDays": 7
		},
		"topicSeparator": " "
	}
}
```

OS: Ubuntu 23.04

My cli: https://github.com/bader-nasser/pdftools

I'm not sure if this is a bug or I'm missing something!

**Comment by mdonnalley** [comment]
@bader-nasser could you provide more details on what you're seeing? I installed an old version of your CLI (0.16.0) and then ran `--help` and saw the warning message

![Screenshot 2023-09-11 at 8 57 18 AM](https://github.com/oclif/plugin-warn-if-update-available/assets/10244328/8d012db6-b7ec-48ee-81a2-7bb78de2b9b3)

**Comment by mdonnalley** [comment]
@bader-nasser Do you have this file, `~/.cache/pdftools/version`? If so, what are the contents?


It's possible you could have gotten yourself in a weird state for whatever reason. In which, case you can force that cache to update by setting `PDFTOOLS_FORCE_VERSION_CACHE_UPDATE=true`

**Comment by bader-nasser** [comment]
{"latest":"0.16.0","current":"0.16.0","authorization":""}

Thank you, it works now after using `PDFTOOLS_FORCE_VERSION_CACHE_UPDATE=true`.
