### ISSUE TITLE
Message about available update is not shown

### ISSUE THREAD

**Issue by Igorgro** [oclif/plugin-warn-if-update-available#612]
**Describe the bug**
When trying to used this plugin, it shows nothing even if new version available. Technical files inside `.cache` directory are created as expected.

**To Reproduce**
Install the plugin and configure it accordingly to README.

**Expected behavior**
Warning about update available is correctly printed

**Screenshots**
-

**Environment (please complete the following information):**

- OS & version: Arch Linux, Node.js 
- Shell/terminal & version: zsh

**Additional context**
I tried to investigate this issue by myself and this is what I found. The issue is cause by this block of code:
https://github.com/oclif/plugin-warn-if-update-available/blob/main/src/hooks/init/check-update.ts#L167-L172
When lodash is imported using dynamic import, it returns `{ default: { ..., template: ..., .... }}` instead of `{ ..., template: ..., }` which means that `lodash.template(message)` call is incorrect and should be replaced `lodash.default.template(message)`. If I replace it in such way, everything works as expected. Otherwise (currently) it throws `Uncaught TypeError: lodash.template is not a function`.

**Comment by mdonnalley** [comment]
Thanks @Igorgro for tracking down the source of the problem. I've got a PR now that I'll merge once it passes CI
